nelmio_cors:
        defaults:
            origin_regex: true
            allow_credentials: true
            allow_origin: ['*']
            allow_headers: ['Authorization', 'Content-Type']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            expose_headers: ['Link']
            max_age: 3600
        paths:
            '^/': ~